BookStore/Models/BookMovement.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookMovement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BookMovement()
        {
            this.BookMovementStatuses = new HashSet<BookMovementStatus>();
        }
    
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public int BookId { get; set; }
        public int BookMovement1 { get; set; }
        public int BookCount { get; set; }
        public System.DateTime DateMovement { get; set; }
        public Nullable<int> CurrentStatus { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookMovementStatus> BookMovementStatuses { get; set; }
        public virtual Status Status { get; set; }
    }
}

BookStore/Controllers/LibrarianController.cs
using BookStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace BookStore.Controllers
{
    [Authorize]
    public class LibrarianController : Controller
    {
        private BookStoreEntities db = new BookStoreEntities();

        // GET: Librarian
        public ActionResult Index()
        {
            SelectList Users = new SelectList(db.Users, "Email", "Email");

            ViewBag.UserID = Users;
            ViewBag.result = "Вы не авторизованы";
            if (User.Identity.IsAuthenticated)
            {
                ViewBag.result = "Вы авторизированы как " + User.Identity.Name; 

            }
            return View();
        }

        [HttpPost]
        public ActionResult BookMovements( string Id, string StatusId)
        {
            StringBuilder SQL = new StringBuilder();

            SQL.Append(@" declare @Id int="+ Id+ ",@StatusId int=" + StatusId +
                @" begin tran
  update b
  set Actual = 0
  from BookMovementStatuses b where b.BookMovementId =@Id

    update b
  set CurrentStatus = @StatusId
  from BookMovementS b where b.Id = @Id

  INSERT INTO[dbo].[BookMovementStatuses]
        ([BookMovementId]
          ,[StatusId]

          ,[Actual])
select @Id,@StatusId,1
  commit tran select '1'");
            string strSQL = SQL.ToString();
            List<string> list = BookStoreProvider.db.Database.SqlQuery<string>(strSQL).ToList();



            return View(BookStoreProvider.db.BookMovements.ToList());
        }
     
       
        public ActionResult BookMovements(string UserEmail)
        {
            return PartialView(BookStoreProvider.db.BookMovements.Where(u => u.User.Email == UserEmail || u.User.Email =="").ToList());
        }
    [HttpPost]
        public ActionResult partialBuy(string id, string ch, string countb)
        {
            string res = id.Replace("Check_", "");
            StringBuilder SQL = new StringBuilder();

            SQL.Append("INSERT INTO BookMovements (UserId, BookId, BookMovement, BookCount,CurrentStatus) " +

                "Select Id ," + res + ",1," + countb.ToString() + ",1 from Users where Email = '" + User.Identity.Name + "' Select '1'");
            string strSQL = SQL.ToString();
            List<string> list = BookStoreProvider.db.Database.SqlQuery<string>(strSQL).ToList();



            return View(BookStoreProvider.UserBookRet());
        }
        public ActionResult PartialIndex(string bn)
        {
            return View(BookStoreProvider.db.Books.Where(b => b.Name.Contains(bn)).ToList());
        }
        // GET: Librarian/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Librarian/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Librarian/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Librarian/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Librarian/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Librarian/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Librarian/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

BookStore/Views/Librarian/BookMovements.cshtml
@model IEnumerable<BookStore.Models.BookMovement>



<table class="table">
    <thead style="position: absolute; background-color:white">
        <tr>

            <th style="width:16vw">
                Количество книг

            </th>
            <th style="width:16vw">
                Дата заказа

            </th>
            <th style="width:16vw">
                Название

            </th>
            <th style="width:18.7vw">
                Email пользователя

            </th>
            <th style="width:16vw">
                Статус книги

            </th>
            <th style="width:16vw"></th>
        </tr>
    </thead>
    <tr><th style="background-color:white">&#160</th></tr>
    <tbody style="margin-top:500px">
        @foreach (var item in Model)
        {

            <tr>

                <td style="width:16vw">
                    @Html.DisplayFor(modelItem => item.BookCount)
                </td>
                <td style="width:16vw">
                    @Html.DisplayFor(modelItem => item.DateMovement)
                </td>
                <td style="width:16vw">
                    @Html.DisplayFor(modelItem => item.Book.Name)
                </td>
                <td style="width:16vw">
                    @Html.DisplayFor(modelItem => item.User.Email)
                </td>
                <td style="width:16vw">
                    @Html.DisplayFor(modelItem => item.Status.StatusName)
                </td>

                <td style="width:16vw">
                    <p>
                        @{
                            if (item.Status != null && item.Status.Id == 1)
                            {

                                <input type="button" id="@item.Id" onclick="BookMovements(@item.Id,2);" value="Выдать">


                            }
                            else if (item.Status != null && item.Status.Id == 3)
                            {

                                <input type="button" id="@item.Id" onclick="BookMovements(@item.Id,5);" value="вернуть книгу">


                            }

                        }
                    </p>
                </td>


            </tr>

        }
    </tbody>

</table>

BookStore/Views/Librarian/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout_2.cshtml";
}

<h3>Список пользователей</h3>
@Html.DropDownList("UserID", ViewBag.UserID as SelectList, new { onchange = "PartialIndexButton(this)" })
 
<div id="PartialIndex" style="overflow:scroll; width:100%; height:400px">
    @Html.Action("BookMovements", "Librarian")
</div>

<script type="text/javascript">
    function PartialIndexButton(th) {
        //var bn = $("#bn").val();
        var UserEmail = $(th).val();
        var jqxhr = $.get('@Url.Action("BookMovements", "Librarian")', { 'UserEmail': UserEmail });
        jqxhr.done(function (data) {
            $('#PartialIndex').html(data);
        });
        jqxhr.fail(function (data) {
            $('#PartialIndex').html("ОШИБКА!");
        });
    }

    function BookMovements(Id,StatusId) {

        var jqxhr = $.post('@Url.Action("BookMovements")', { 'Id': Id, 'StatusId': StatusId});
        jqxhr.done(function (data) {
            $('#PartialIndex').html(data);
        });
        jqxhr.fail(function (data) {
            $('#PartialIndex').html("ОШИБКА!");
        });

    }

</script>